### ISSUE TITLE
Error on hoobs

### ISSUE THREAD

**Issue by The-Paw** [NikDevx/homebridge-philips-air#124]
6.2.2021, 22:47:35 [Philips Air] [1000i] Unable to load firmware info: Error: unpad(): found a padding byte of 185 instead of 95 at position 140

After restart:

6.2.2021, 22:55:30 [Philips Air] [1000i] Unable to load status info: Error: unpad(): found a padding byte of 172 instead of 99 at position 124

**Comment by Sunoo** [comment]
Does the plugin still work for you?

**Comment by The-Paw** [comment]
> Does the plugin still work for you?

Homekit-Automation starts only, if I select the room with the 1000i in the Home-App. Verry strange.

**Comment by Sunoo** [comment]
Bringing up the room will query the device again. Not sure why it fails on startup and works later though.

**Comment by The-Paw** [comment]
On hoobs 3.3.3 here's the LOG:

7.3.2021, 11:48:51 [HOOBS 691B@Keller@Active carbon filter@Filter Change Indication] characteristic value expected number and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@Active carbon filter@Filter Life Level] characteristic value expected float and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@HEPA filter@Filter Change Indication] characteristic value expected number and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@HEPA filter@Filter Life Level] characteristic value expected float and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@Keller@PM2.5 Density] characteristic value expected float and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@Keller@PM2.5 Density] characteristic value expected float and received undefined
7.3.2021, 11:48:51 [HOOBS 691B@Keller@Keller@Active] characteristic value expected number and received undefined
