### ISSUE TITLE
Can’t see the new plugin version on hoobs 

### ISSUE THREAD

**Issue by dvd2000k** [NikDevx/homebridge-philips-air#155]
On hoobs I can’t see the new update. If I search for Philips-air plugin it give me the 2.3.2 as the latest version.

**Comment by NikDevx** [comment]
> On hoobs I can’t see the new update. If I search for Philips-air plugin it give me the 2.3.2 as the latest version.

@dvd2000k Hi!
I didn't get access to the hoobs repo. So I can only publish to npm and git

**Comment by dvd2000k** [comment]
Hoobs use the same source as Homebridge for plugins. Will try to ask hoobs support.

**Comment by NikDevx** [comment]
Hello @Sunoo 
Can you give me access to Hoobs repo please?

**Comment by Sunoo** [comment]
There is no separate repo for HOOBS, they just pull from NPM.

**Comment by NikDevx** [comment]
> There is no separate repo for HOOBS, they just pull from NPM.

I have already posted to npm.
Will it appear in Hoobs later?

**Comment by Sunoo** [comment]
Not sure how frequently they update. If it doesn’t show after a bit either reach out to them, or I could let them know something is up.

**Comment by NikDevx** [comment]
> Not sure how frequently they update. If it doesn’t show after a bit either reach out to them, or I could let them know something is up.

Okay. Thank you!

**Comment by dvd2000k** [comment]
If you go to https://plugins.hoobs.org, search for Philips air, it show 2.3.2. Don't know why, but other plugins are updated in real time.

**Comment by NikDevx** [comment]
> If you go to https://plugins.hoobs.org, search for Philips air, it show 2.3.2. Don't know why, but other plugins are updated in real time.

@dvd2000k can you download or update from npm?

**Comment by Sunoo** [comment]
I’ve reached out to the HOOBS folks, we’ll see if they can provide any clarity on this.

**Comment by dvd2000k** [comment]
> > If you go to https://plugins.hoobs.org, search for Philips air, it show 2.3.2. Don't know why, but other plugins are updated in real time.
> 
> @dvd2000k can you download or update from npm?

In hoobs you can install plugin only from UI. 
It doesn’t support plugin installation through terminal.

**Comment by Sunoo** [comment]
This should be fixed now. I checked myself and am now seeing version 3.0.3 there.

The person at HOOBS who fixed it also pointed this out:

> If they want the author to change. They need to update the author in the package.json. Currently it is this.
"author": {
    "name": "David Maher | Nik_Dev"
},
If should like something like this.
"author": {
    "name": "Nik_Dev",
    "email": "andrievskiy_nikita@yahoo.com"
},
The plugin site links the email to the HOOBS ID email and allows them to edit the plugin. Currently you are marked as the author.

If you want to still credit me, it’s probably better to do so in the Readme than in the package.json so it doesn’t have that issue.

**Comment by NikDevx** [comment]
> This should be fixed now. I checked myself and am now seeing version 3.0.3 there.
> 
> The person at HOOBS who fixed it also pointed this out:
> 
> > If they want the author to change. They need to update the author in the package.json. Currently it is this.
> > "author": {
> > "name": "David Maher | Nik_Dev"
> > },
> > If should like something like this.
> > "author": {
> > "name": "Nik_Dev",
> > "email": "[andrievskiy_nikita@yahoo.com](mailto:andrievskiy_nikita@yahoo.com)"
> > },
> > The plugin site links the email to the HOOBS ID email and allows them to edit the plugin. Currently you are marked as the author.
> 
> If you want to still credit me, it’s probably better to do so in the Readme than in the package.json so it doesn’t have that issue.

@Sunoo Thank you!

**Comment by NikDevx** [comment]
> > > If you go to https://plugins.hoobs.org, search for Philips air, it show 2.3.2. Don't know why, but other plugins are updated in real time.
> > 
> > 
> > @dvd2000k can you download or update from npm?
> 
> In hoobs you can install plugin only from UI.
> It doesn’t support plugin installation through terminal.

@dvd2000k check Hoobs tomorrow.
