### ISSUE TITLE
Many warnings and errors with actual versions

### ISSUE THREAD

**Issue by 011V32** [NikDevx/homebridge-philips-air#156]
Hello,

I have Homebridge v1.3.4 and homebridge-philips-air v3.0.4 and get following warnings and error with an Philips AC2729:

> [29.3.2021, 21:06:00] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:00] [Philips Air] [Philips AC2729] Unable to load humidity_sensor info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:01] [Philips Air] [Philips AC2729] Unable to load firmware info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:01] [Philips Air] [Philips AC2729] Unable to load status info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:01] [Philips Air] [Philips AC2729] Unable to load filter info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Current Air Purifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Target Air Purifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Lock Physical Controls': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Air Quality': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'PM2.5 Density': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Change Indication': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Active': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Current Humidifier-Dehumidifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Target Humidifier-Dehumidifier State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Relative Humidity Humidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Relative Humidity Dehumidifier Threshold': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

> [29.3.2021, 21:06:02] [Philips Air] [Philips AC2729] Unable to load water level info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:02] [Philips Air] [Philips AC2729] Unable to load temperature_sensor info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:03] [Philips Air] [Philips AC2729] Unable to load humidity_sensor info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:03] [Philips Air] [Philips AC2729] Unable to load status info: Error: connect ECONNREFUSED 192.168.0.39:80

> [29.3.2021, 21:06:04] [Philips Air] [Philips AC2729] Unable to load filter info: Error: connect ECONNREFUSED 192.168.0.39:80

would be great if you could fix them.

Regards.

**Comment by NikDevx** [comment]
Read this one https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

If you see this message in the log, the plugin attempted to set an invalid value for a certain characteristic. This is just an informative warning message, Homebridge will automatically correct the value to a valid one.

**Comment by 011V32** [comment]
And what about the errors?

Regards.

**Comment by 011V32** [comment]
Hello,

my config is:

`        {
            "devices": [
                {
                    "name": "Philips AC2729",
                    "ip": "192.168.0.39",
                    "protocol": "http",
                    "allergic_func": true,
                    "humidity_sensor": true,
                    "humidifier": true
                }
            ],
            "name": "Philips Air",
            "platform": "philipsAir"
        }`

I also changed the permissions for hum.txt and temp.txt to 777 (under /usr/lib/node_modules/homebridge-philips-air/sensor/)
Restarted all and still error.

I installed the plugin over the Homebridge Visualization.

What do you mean with "And did you install philips-air?" I couldn't find an Info on your GitHub https://github.com/NikDevx/homebridge-philips-air for additional things than the plugin?
Thx.

Regards.

**Comment by NikDevx** [comment]
I mean this plugin **https://github.com/NikDevx/philips-air** to work properly
https://www.npmjs.com/package/philips-air

**Comment by 011V32** [comment]
Hi,

I read at this article that the newer Firmware only supports encrypted CoaP:
https://github.com/rgerganov/py-air-control/issues/35

So I tried the steps you wrote to install the Coal support, but I get the following warning that the brach or tag 89d5173 doesn't exist:
```
sudo pip3 install -U git+https://github.com/Tanganelli/CoAPthon3@89d5173
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/Tanganelli/CoAPthon3@89d5173
  Cloning https://github.com/Tanganelli/CoAPthon3 (to revision 89d5173) to /tmp/pip-req-build-jqr44h2v
  Did not find branch or tag '89d5173', assuming revision or ref.
Building wheels for collected packages: CoAPthon3
  Running setup.py bdist_wheel for CoAPthon3 ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-mared6nm/wheels/63/8f/99/012c8b6374fe3a573d1106deeac84fa79e12b5be12fa19d457
Successfully built CoAPthon3
Installing collected packages: CoAPthon3
  Found existing installation: CoAPthon3 1.0.1
    Uninstalling CoAPthon3-1.0.1:
      Successfully uninstalled CoAPthon3-1.0.1
Successfully installed CoAPthon3-1.0.1
```

Regards
