### ISSUE TITLE
I can't add a second purifier successfully 

### ISSUE THREAD

**Issue by mj16792** [NikDevx/homebridge-philips-air#159]
My first AC2889 purifier has been working great with this plugin. I now have a AC1214 which I'm trying to add and I can't for the life of me get it to work. I've set it up in exactly the same way using the correct IP address. The device name for this appears as MiCO instead of the PHILIPS-DHCP-CLIENT name which is what the AC2889 appears as.

I'm not massively good at this stuff so I may have just missed something obvious, or not understood the CoAP options.

I get a series of these errors for example:
[Philips Air Purifier] [Bedroom Air Purifier] Unable to load status info: Error: connect ECONNREFUSED 192.168.178.58:80

**Comment by mj16792** [comment]
My config file for this plugins looks like this: 

 "devices": [
                {
                    "name": "Downstairs Air Purifier",
                    "ip": "192.168.178.46",
                    "protocol": "http",
                    "sleep_speed": true,
                    "light_control": false,
                    "allergic_func": true
                },
                {
                    "name": "Bedroom Air Purifier",
                    "ip": "192.168.178.58",
                    "protocol": "http",
                    "sleep_speed": false,
                    "allergic_func": true
                }
            ],
            "name": "Philips Air Purifier",
            "timeout_seconds": 20,
            "platform": "philipsAir"

**Comment by NikDevx** [comment]
Why are you using `"protocol": "http"`in config, but you asking about Coap?

**Comment by mj16792** [comment]
Yep, I was being slightly Homebr

**Comment by mj16792** [comment]
I was being Homebridge illiterate. I assumed as this was an older model it was http, but turns out its COAP. 

Whenever I use COAP or Plain COAP I get a string of errors though, even though I can find the purifier on my network now.

For example:

This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

And:

[Bedroom Purifier] Unable to load filter info: Error: Command failed: python3 /usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.178.58 --protocol coap --status
Give up on message From None, To ('192.168.178.58', 5683), CON-2602, POST-ZF, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] AF0BBB79...8 bytes
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 123, in <module>
    main()
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 99, in main
    c = CoAPCli(args.ipaddr)
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 15, in __init__
    self._client = CoAPAirClient(host, port, False)
  File "/usr/local/lib/python3.7/dist-packages/pyairctrl/coap_client.py", line 80, in __init__
    self._sync()
  File "/usr/local/lib/python3.7/dist-packages/pyairctrl/coap_client.py", line 96, in _sync
    raise Exception("sync timeout")
Exception: sync timeout

Seems to be slowing down my entire Homebridge set up as it works through these errors very few mins

**Comment by NikDevx** [comment]
You should open issue in pyair!
https://github.com/rgerganov/py-air-control

**Comment by mj16792** [comment]
Ah ok. Just realised the errors also happen on my http device too

This plugin generated a warning from the characteristic 'Air Quality': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

**Comment by NikDevx** [comment]
> Ah ok. Just realised the errors also happen on my http device too
> 
> This plugin generated a warning from the characteristic 'Air Quality': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

This is a good warning.
I have this warning too and the plugin works fine.

Try to install from the beginning like in the readme
https://github.com/NikDevx/homebridge-philips-air#readme
