### ISSUE TITLE
Error: spawnSync python3 ETIMEDOUT

### ISSUE THREAD

**Issue by 011V32** [NikDevx/homebridge-philips-air#162]
Hi,

with the latest version (V3.2.2 and V3.2.1 sure, and probably versions bevore) i get following errors:

```
[Philips Air] [Philips AC2729] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
[Philips Air] [Philips AC2729] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
[Philips Air] [Philips AC2729] Unable to load filter info: Error: spawnSync python3 ETIMEDOUT
[Philips Air] [Philips AC2729] Unable to load humidity_sensor info: Error: spawnSync python3 ETIMEDOUT
```
With later versions it worked allready without errors.

Regards.

**Comment by NikDevx** [comment]
> Hi,
> 
> with the latest version (V3.2.2 and V3.2.1 sure, and probably versions bevore) i get following errors:
> 
> ```
> [Philips Air] [Philips AC2729] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
> [Philips Air] [Philips AC2729] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
> [Philips Air] [Philips AC2729] Unable to load filter info: Error: spawnSync python3 ETIMEDOUT
> [Philips Air] [Philips AC2729] Unable to load humidity_sensor info: Error: spawnSync python3 ETIMEDOUT
> ```
> 
> With later versions it worked allready without errors.
> 
> Regards.

Turn off you accessory from socket on 10 seconds and reboot your wi-fi.
And try new version of plugin.
