### ISSUE TITLE
SyntaxError: Unexpected token U in JSON at position 0

### ISSUE THREAD

**Issue by 011V32** [NikDevx/homebridge-philips-air#163]
Hi,

i updated the plugin from V3.2.2 to V3.2.5 and now I get the following error after reboot homebridge:

```
SyntaxError: Unexpected token U in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/lib/node_modules/homebridge-philips-air/src/index.ts:215:26
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```
(Homebridge v1.3.4)

Regards.

**Comment by NikDevx** [comment]
Try in console on raspberry pi or what your using.

`python3 /usr/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr <ip from  accesory> --protocol coap --status`

Did you get data?

**Comment by NikDevx** [comment]
The new version 3.2.6 adds a fix

**Comment by 011V32** [comment]
Fix worked for me. Thx

**Comment by NikDevx** [comment]
> Fix worked for me. Thx

You are welcome
