### ISSUE TITLE
Got SIGINT, shutting down Homebridge...

### ISSUE THREAD

**Issue by chrispi68** [NikDevx/homebridge-philips-air#168]
This plug causes a home bridge shutdown and permanent reboots of home bridge. After deactivating the plugin, everything works fine.

I noticed this problem today and I didi not have this problem in the past with this plugin. I am running the latest version 3.5.0. There is no additional information in the log.

**Comment by NikDevx** [comment]
Give me the logs with debug mode

**Comment by chrispi68** [comment]
How can I enable debug mode? I use Homebridge UI.

**Comment by NikDevx** [comment]
Google is your friend :)
