### ISSUE TITLE
'Model': characteristic value expected string and received undefined.

### ISSUE THREAD

**Issue by Smexhy** [NikDevx/homebridge-philips-air#170]
Hello, I am getting the following warning after each homebridge startup:

`[7/10/2021, 2:44:30 AM] [homebridge-philips-air] This plugin generated a warning from the characteristic 'Model': characteristic value expected string and received undefined. See https://git.io/JtMGR for more info`

Is there any fix to this? I tried specifying the model in the config, without the luck.

**Comment by NikDevx** [comment]
https://github.com/rgerganov/py-air-control/issues/93
