### ISSUE TITLE
After the update AC1214/10, error all the time.

### ISSUE THREAD

**Issue by stoyanland** [NikDevx/homebridge-philips-air#171]
13.07.2021 г., 16:04:55Philips Air BridgeERRORGive up on message From None, To ('192.168.0.125', 5683), CON-43628, GET-None, [Uri-Path: sys, Uri-Path: dev, Uri-Path: status, Observe: 0, ] No payload
13.07.2021 г., 16:04:55Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@@Model] characteristic value expected string and received undefined
13.07.2021 г., 16:04:55Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@@Firmware Revision] characteristic value expected string and received undefined
13.07.2021 г., 16:04:58Philips Air BridgeERRORGive up on message From None, To ('192.168.0.125', 5683), CON-40965, GET-None, [Uri-Path: sys, Uri-Path: dev, Uri-Path: status, Observe: 0, ] No payload
13.07.2021 г., 16:04:58Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Living Room Purifier@Active] characteristic value expected valid finite number and received "undefined" (undefined)
13.07.2021 г., 16:04:58Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Living Room Purifier@Current Air Purifier State] characteristic value expected valid finite number and received "NaN" (number)
13.07.2021 г., 16:04:58Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Living Room Purifier@Lock Physical Controls] characteristic value expected valid finite number and received "undefined" (undefined)
13.07.2021 г., 16:04:58Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Air quality@Air Quality] characteristic value expected valid finite number and received "NaN" (number)
13.07.2021 г., 16:04:58Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Air quality@PM2.5 Density] characteristic value expected valid finite number and received "undefined" (undefined)
13.07.2021 г., 16:05:00Philips Air BridgeERRORGive up on message From None, To ('192.168.0.125', 5683), CON-62513, GET-None, [Uri-Path: sys, Uri-Path: dev, Uri-Path: status, Observe: 0, ] No payload
13.07.2021 г., 16:05:00Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Pre-filter@Filter Life Level] characteristic value expected valid finite number and received "NaN" (number)
13.07.2021 г., 16:05:00Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@Active carbon filter@Filter Life Level] characteristic value expected valid finite number and received "NaN" (number)
13.07.2021 г., 16:05:00Philips Air BridgeERROR[Philips Air Bridge F9F0@Living Room Purifier@HEPA filter@Filter Life Level] characteristic value expected valid finite number and received "NaN" (number)

**Comment by stoyanland** [comment]
Now after v.3.5.2, it shows air purifier always on, after I press off, 1 min later shows on again, using coap protocol.

**Comment by NikDevx** [comment]
https://github.com/rgerganov/py-air-control/issues/93

**Comment by stoyanland** [comment]
Thank, i miss this update. But how i am supposed to edit it?
