### ISSUE TITLE
Switch to aioairctrl?

### ISSUE THREAD

**Issue by sieren** [NikDevx/homebridge-philips-air#174]
Hey there,

I'd like to point out aioairctrl (https://github.com/rgerganov/py-air-control/issues/93) which seems to solve the issues of unresponsive updates from py-air-ctrl as the latest Philips FW seems to have switched to a more passive observer model and doesn't reliable respond to status requests anymore (see the issue).

I've been hackishly rewriting `homebridge-philips-air` to use this library and the results have been pretty good. Both commands get sent a lot faster and without a big delay as well as the polling is much improved and reacts pretty quickly (as it's passively observing the purifiers vs. actively polling).

https://github.com/sieren/homebridge-philips-air/commit/aa2752afd49f85939b6f22d69ff52ae0ed405f16 this is extremely hacky as I ditched a bunch of code in favor of making it work wiht my own unit first, refactored accessories to their own class and added support for Eve Room 2 simulation to display pm2.5 values in the Eve Home app.

**Comment by NikDevx** [comment]
Hello 
Thanks for you work )

I will Switch to aioairctrl later

**Comment by NikDevx** [comment]
Or you can change and pull request

**Comment by inwaar** [comment]
Hi Nik, thanks for the homebridge plugin!
Do you consider moving from the python dependencies? I've seen a pure JS integration (https://github.com/biemond/com.athom.philipsair) and it seems working with my AC3829/50.

**Comment by iharosi** [comment]
@NikDevx any update on this?

**Comment by NikDevx** [comment]
https://github.com/seydx/homebridge-philipsair-platform
