### ISSUE TITLE
Error: spawnSync python3 ETIMEDOUT still not fixed

### ISSUE THREAD

**Issue by adrmnt** [NikDevx/homebridge-philips-air#175]
Hi,

I saw that this issues was discussed before but unfortunately for me the possible fix doesn't worked. Do you have any update or advice? 

_Unable to get data for polling: Error: spawnSync python3 ETIMEDOUT.
If your have "Error: spawnSync python3 ETIMEDOUT" your need unplug the accessory from outlet for 10 seconds and plug again._

Thank you!

**Comment by niwre2019** [comment]
Hi,

I have exactly the same problem, the workaround didn't help me either.
I regularly get the error message "_Unable to get data for polling: Error: spawnSync python3 ETIMEDOUT_". 
It would be great if there was a solution for this. 

Thanks very much.

**Comment by NikDevx** [comment]
@adrmnt, @niwre2019 Hi.
This is error coming not from my plugin.

https://github.com/rgerganov/py-air-control/issues/93

**Comment by NikDevx** [comment]
https://github.com/seydx/homebridge-philipsair-platform
