### ISSUE TITLE
AC1214/10 on hoobs 4.1.11 and PlugIn Version 2.3.4 .. newer doesn't work, too!

### ISSUE THREAD

**Issue by The-Paw** [NikDevx/homebridge-philips-air#176]
7.11.2021, 12:58:33HOOBSFEHLER[HOOBS 691B@Keller@Keller@PM2.5 Density] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:33HOOBSFEHLER[HOOBS 691B@Keller@Keller@PM2.5 Density] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:33HOOBSFEHLER[HOOBS 691B@Keller@Keller@Active] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:33HOOBSFEHLER[HOOBS 691B@Keller@Keller@Active] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:33HOOBSFEHLER[HOOBS 691B@Keller@Keller@Target Air Purifier State] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:34HOOBSFEHLER[HOOBS 691B@Keller@Keller@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)
7.11.2021, 12:58:34HOOBSFEHLER[HOOBS 691B@Keller@Keller@Lock Physical Controls] characteristic value expected valid finite number and received "undefined" (undefined)

**Comment by NikDevx** [comment]
https://github.com/seydx/homebridge-philipsair-platform

**Comment by The-Paw** [comment]
> https://github.com/seydx/homebridge-philipsair-platform

What does it mean .. should I use your posted PlugIn??

**Comment by The-Paw** [comment]
Your posted Link doesn't work, too :-((
